[package]
name = "calculate-etag"
version = "0.1.0"
authors = ["Bernard Niset <bernard.niset@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
err-derive = "0.1"
rust-crypto = "0.2.36"
structopt = "0.3.5"